### ISSUE TITLE
How to change the input pictures size?

### ISSUE THREAD

**Issue by SunJJ1996** [Oliverbihop/Attention_Module_Densenet#1]
I have tried you code and find that I could only use the input pictures with 32*32. Or it will alert this error:

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x7680 and 1920x10)`

when I tried to use 128*128 as the input feature map.

How to revise this project to fix this problem? Thank you.
@Oliverbihop

**Comment by Oliverbihop** [comment]
Hi, if you are running densenet-CBAM model , you just modify the last layer (Fully connected layers) .

**Comment by SunJJ1996** [comment]
@Oliverbihop 
Thank you for you reply. Can you show me how to modify the last layer in detail?

`class DenseNet(nn.Module):
    def __init__(self, block, nblocks, growth_rate=12, reduction=0.5, num_classes=10):
        super(DenseNet, self).__init__()
        self.growth_rate = growth_rate

        num_planes = 2 * growth_rate
        self.conv1 = nn.Conv2d(3, num_planes, kernel_size=3, padding=1, bias=False)

        self.dense1 = self._make_dense_layers(block, num_planes, nblocks[0])
        num_planes += nblocks[0] * growth_rate
        out_planes = int(math.floor(num_planes * reduction))
        self.trans1 = Transition(num_planes, out_planes)
        num_planes = out_planes

        self.dense2 = self._make_dense_layers(block, num_planes, nblocks[1])
        num_planes += nblocks[1] * growth_rate
        out_planes = int(math.floor(num_planes * reduction))
        self.trans2 = Transition(num_planes, out_planes)
        num_planes = out_planes

        self.dense3 = self._make_dense_layers(block, num_planes, nblocks[2])
        num_planes += nblocks[2] * growth_rate
        out_planes = int(math.floor(num_planes * reduction))
        self.trans3 = Transition(num_planes, out_planes)
        num_planes = out_planes

        self.dense4 = self._make_dense_layers(block, num_planes, nblocks[3])
        num_planes += nblocks[3] * growth_rate

        self.bn = nn.BatchNorm2d(num_planes)
        print(num_planes)
        self.linear = nn.Linear(num_planes, num_classes)

    def _make_dense_layers(self, block, in_planes, nblock):
        layers = []
        for i in range(nblock):
            layers.append(block(in_planes, self.growth_rate))
            in_planes += self.growth_rate
        return nn.Sequential(*layers)

    def forward(self, x):
        # print(x.size())
        out = self.conv1(x)
        out = self.trans1(self.dense1(out))
        out = self.trans2(self.dense2(out))
        out = self.trans3(self.dense3(out))
        out = self.dense4(out)
        out = F.avg_pool2d(F.relu(self.bn(out)), 4)
        out = out.view(out.size(0), -1)
        out = self.linear(out)
        return out`

Thank you a lot for your help!

**Comment by Oliverbihop** [comment]
'''self.linear = nn.Linear(num_planes, num_classes)'''
You try to change num_planes=7680.

**Comment by SunJJ1996** [comment]
> '''self.linear = nn.Linear(num_planes, num_classes)''' You try to change num_planes=7680.

Thank you for your reply.

When I changed the input feature map to 128*128 and changed the code you said into:
`self.linear = nn.Linear(7680, num_classes)`

It jumped a RuntimeError:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x38400 and 7680x10)`

**Comment by Oliverbihop** [comment]
could you please print the numplanes.shape because this code have no longer on my computer.

**Comment by SunJJ1996** [comment]
num_planes is an INT object. So it does not have 'shape'.
`AttributeError: 'int' object has no attribute 'shape'`

You have added a print in this place:

`        self.dense4 = self._make_dense_layers(block, num_planes, nblocks[3])`
       ` num_planes += nblocks[3] * growth_rate`
    `    self.bn = nn.BatchNorm2d(num_planes)`
        `print(num_planes)`
    `    self.linear = nn.Linear(7680, num_classes)`

And the result of print(num_planes) is 1920 in this code.

**Comment by SunJJ1996** [comment]
I have solved this problem. All I need is to put a breakpoint into `out = self.linear(out)` then, catch the current result of OUT. Finally, replace num_planes in `self.linear = nn.Linear(num_planes, num_classes)` using the second dimension of OUT.
